#!/bin/bash

check() {
    require_binaries "$WORK_DIR/girie" || return 1
    return 255
}

depends() {
    echo "base"
    return 0
}

install() {
    # binaries.
    inst "$WORK_DIR/girie" "/usr/local/bin/girie"
}